Add script to push jar file to nexus
Datatamer/elasticsearch pull request #5
Opened 2017-03-03 02:24 UTC by tonyastolfi

2017-03-03 15:40 UTC, laferrieren commented
Some docs would be nice, a comment at the head of the file or on the readme would be nice

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/datatamer/elasticsearch/5#-:-KeJp0qpxXlFn--08Eya:bufuq3p)*
<!-- Sent from Reviewable.io -->

2017-03-06 18:16 UTC, data-tamer-vgp requested changes

2017-03-06 18:16 UTC, data-tamer-vgp commented on pushToTamrNexus.sh
> +    mvn deploy:deploy-file -Dfile=$(fullfile $1) \
Might want to check for Maven version being some minimum. Older versions won't do the right thing.

2017-03-07 14:40 UTC, tonyastolfi commented
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pushToTamrNexus.sh, line 13 at r1](https://reviewable.io:443/reviews/datatamer/elasticsearch/5#-KeGywI0En8w7ydz_Zij-r1-13:-KedC_byKpYAUa-I9GnY:b-896fix) ([raw file](https://github.com/datatamer/elasticsearch/blob/249b9549a9dc4673c24aa3a857ba3cd71821fb80/pushToTamrNexus.sh#L13)):*
<details><summary><i>Previously, data-tamer-vgp wrote…</i></summary><blockquote>

Might want to check for Maven version being some minimum. Older versions won't do the right thing.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/datatamer/elasticsearch/5)*
<!-- Sent from Reviewable.io -->

2017-03-07 15:08 UTC, data-tamer-vgp approved these changes

2017-03-07 15:08 UTC, data-tamer-vgp commented
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/datatamer/elasticsearch/5)*
<!-- Sent from Reviewable.io -->

2017-03-07 16:42 UTC, laferrieren commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/datatamer/elasticsearch/5#-:-KeddXSz_zH8gYi91vXt:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2017-03-08 22:21 UTC, merged